### ISSUE TITLE
Help with attestation

### ISSUE THREAD

**Issue by Jonas-Metzger** [aws-samples/aws-nitro-enclaves-workshop#16]
Hi! I'm trying to understand how to request the attestation document inside the enclave using python (specifically, with the `user_data`  field populated with a custom string generated inside the enlcave). Could you please help me with this?

**Comment by jdbean** [comment]
Hello and thank you for your inquiry. I notice that you've posted a similar issue for the Nitro Enclaves NSM API. I'll defer to the response from @petreeftime  at https://github.com/aws/aws-nitro-enclaves-nsm-api/issues/9#issuecomment-885507903 .

I'm closing this issue in favor of centralize discussion on this topic there.
